name: dawolang
description: Word-based command and message language. Always grateful to dartlang, our little brother.
version: 0.1.0
homepage: https://dawopack.blogspot.fi/search/label/dawolang

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  #  path: ^+2.1.7

dev_dependencies:
  build_runner: ^2.1.7
