name: dawolang
description: Word-based command and message language. Always grateful to dartlang, our little brother.
version: 0.2.0
homepage: https://dawopack.blogspot.fi/search/label/dawolang

environment:
  sdk: ^3.1.5

dependencies:
  #  path: ^+2.1.7

dev_dependencies:
  build_runner: ^2.1.7
