name: dawolang
description: Word-based command and message language. Always grateful to dartlang, our little brother.
version: 0.0.1
homepage: https://dawopack.blogspot.fi/search/label/dawolang
author: Heikki K Lappalainen <heikkiklappalainen@gmail.com.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
